name: ketall CI
on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Verify go.mod is sane
        run: go mod tidy && git diff --no-patch --exit-code

      - name: golangci-lint
        uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86 # v6.1.0
        with:
          args: --timeout 10m --verbose

      - name: go test
        run: go test ./...
