name: ketall CI
on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.20
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Verify go.mod is sane
      run: go mod tidy && git diff --no-patch --exit-code

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54

    - name: go test
      run:
        go test ./...